# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2022-05-11 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_fixer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='short_url',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
